<a href="https://colab.research.google.com/github/OmkarSolat/Data-Science-in-DevTown/blob/main/DAY17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

More Faster than list

Commands:->

import numpy

import numpy as np

pip install numpy

In [ ]:
import numpy as np
import time

In [ ]:
a = np.random.rand(1000000000)

In [ ]:
a

array([0.37947963, 0.17361886, 0.29731149, ..., 0.30529966, 0.06780225,
       0.56575858])

In [ ]:
# List  (more time required)

start = time.time()
mean_list = sum(a)/len(a)
print(time.time()-start)


72.25315165519714


In [ ]:
mean_list

0.499999093206319

In [ ]:
# Numpy    (less time required)

start = time.time()
mean_np= np.mean(a)
print(time.time()-start)

0.4342062473297119


In [ ]:
mean_np

0.4999990932056776

# Operations

Initializing the NumPy array

In [ ]:
#syntax
arr = np.array()

In [ ]:
# 0D (Zero Dimensional)
arr = np.array(4)
arr

array(4)

In [ ]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [ ]:
type(arr)

numpy.ndarray



*   ndim attribute - It will gonna return the dimensions of the array.



In [ ]:
#0D
arr = np.array(4)


In [ ]:
arr.ndim

0

In [ ]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr.ndim

1

In [ ]:
# 2D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
arr.ndim

2

In [ ]:
 #3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])


In [ ]:
arr.ndim

3

converting into n-dimentional array

In [ ]:
arr = np.array([1,2,3,4],ndmin=10)

In [ ]:
arr.ndim

10

In [ ]:
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])



* Shape - It tells about the size of the array



In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

#3x5 (dimentions)
#row x column

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

# no.of 2D array x row x column

In [ ]:
arr.shape

(2, 2, 4)



*   dtype - It tells about the type of the data



In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array(["apple","mangoes","cherry",9.9])

In [ ]:
arr.dtype

dtype('<U32')


*   size - It tells us the total number of elements



In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.size

15

In [ ]:
#np.size(ndarray,1(row)/0(column))

In [ ]:
np.size(arr,0)

3

In [ ]:
np.size(arr,1)

5



 * Itemsize - It tells us about the length of the single element in bytes


In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.itemsize

8



*  nbytes - returns total bytes

In [ ]:
arr.nbytes

120

In [ ]:
arr = np.array([4])

In [ ]:
arr.itemsize

8

In [ ]:
arr.nbytes

8