<a href="https://colab.research.google.com/github/OmkarSolat/Data-Science-in-DevTown/blob/main/DAY18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CRUD Operations on NumPy array

In [ ]:
import numpy as np

# CREATE

 np.array function -->

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr.ndim

2

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr.ndim

1

np.zeros function -->

In [ ]:
arr = np.zeros(10) #1D
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([10,10])    #2D
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.zeros([10,3,4])    #3D
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

 np.ones function --->

In [ ]:
arr = np.ones([10])
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

 np.empty function --->

In [ ]:
arr = np.empty([4,4])
arr

array([[4.95596151e-310, 0.00000000e+000, 6.60590473e-310,
        6.60588020e-310],
       [6.60590430e-310, 6.60590470e-310, 6.60590473e-310,
        6.60590473e-310],
       [6.60588020e-310, 6.60590467e-310, 6.60590470e-310,
        2.42092166e-322],
       [4.95666656e-310, 6.60590504e-310, 6.60590473e-310,
        6.60586621e-310]])

np.full function -->

In [ ]:
arr = np.full([5,5],18)
arr

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

np.eye() function --> Identity matrix

In [ ]:
arr = np.eye(9)  # 9X9 Identity matrix
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

np.diag() function ---> Diagonal Matrix

In [ ]:
arr = np.diag([10,20,30,40,50,60,70,80,90,100])
arr

array([[ 10,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  20,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  30,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  40,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  50,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  60,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  70,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  80,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  90,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

np.linspace(start,end,no. of elements) ---->

(gives equally distributed values)

In [ ]:
arr = np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

np.random.randint() function ---->


In [ ]:
arr = np.random.randint(1,20,size=(3,3))
arr

array([[17,  1,  4],
       [15,  2, 10],
       [ 7, 18,  3]])

np.arange(start,stop,incre/decre) --->

In [ ]:
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# UPDATE

In [ ]:
arr1 = np.array([1,2,3,4,5])

arr2  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])

arr3  = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                     [7,8,9],
                     [11,12,12]
                  ]
                  ])

#indexing

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1[2]    #1D array

3

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2[1,3]

8

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr3[0,1,1]    #to read element 5

5

In [ ]:
arr3[0,1,1] = 18     # Assigning

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4, 18,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2[1:2]

array([[5, 6, 7, 8]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4, 18,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr3[0,1]

array([ 4, 18,  6])

In [ ]:
arr3[0,1,0:2]         #[array,row,start:end]

array([ 4, 18])

In [ ]:
arr3[0,1][0:2]

array([ 4, 18])

reshape()

In [ ]:
# Create a matrix 3x4, 10 to 500 + elements should be evenly distributed

arr = np.linspace(10,500,12)

In [ ]:
arr.reshape(3,4)
arr

array([ 10.        ,  54.54545455,  99.09090909, 143.63636364,
       188.18181818, 232.72727273, 277.27272727, 321.81818182,
       366.36363636, 410.90909091, 455.45454545, 500.        ])

In [ ]:
arr.reshape(2,3,2)

array([[[ 10.        ,  54.54545455],
        [ 99.09090909, 143.63636364],
        [188.18181818, 232.72727273]],

       [[277.27272727, 321.81818182],
        [366.36363636, 410.90909091],
        [455.45454545, 500.        ]]])

In [ ]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
arr2 = np.array([15,16,17,18])
arr2

array([15, 16, 17, 18])

In [ ]:
np.append([arr1],[arr2],axis=0)

array([[ 1,  2,  3,  4],
       [15, 16, 17, 18]])

In [ ]:
arr1 + arr2

array([16, 18, 20, 22])

In [ ]:
arr1 - arr2

array([-14, -14, -14, -14])

In [ ]:
arr1 * arr2

array([15, 32, 51, 72])

In [ ]:
arr1 / arr2

array([0.06666667, 0.125     , 0.17647059, 0.22222222])