<a href="https://colab.research.google.com/github/OmkarSolat/Data-Science-in-DevTown/blob/main/DAY20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MORE ON NumPy

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])

* stacking

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
np.vstack([arr1,arr2])          #vertical stacking

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [ ]:
np.hstack([arr1,arr2])            #horizontal stacking

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
arr3 = np.array([100,200,300])
arr3

array([100, 200, 300])

In [ ]:
arr4 = np.array([500,600,700])
arr4

array([500, 600, 700])

In [ ]:
np.dstack((arr3,arr4))          #down stacking

array([[[100, 500],
        [200, 600],
        [300, 700]]])

* spliting

In [ ]:
arr3

array([100, 200, 300])

In [ ]:
np.array_split(arr3,4)

[array([100]), array([200]), array([300]), array([], dtype=int64)]

In [ ]:
np.array_split(arr3,2)

[array([100, 200]), array([300])]


* searching

In [ ]:
arr = np.array([1,18,45,7,33,93,17,10,18,7,7,10,45,18])
arr

array([ 1, 18, 45,  7, 33, 93, 17, 10, 18,  7,  7, 10, 45, 18])

In [ ]:
np.where(arr==18)      #returns the indices of given element

(array([ 1,  8, 13]),)

In [ ]:
np.where(arr < 20)

(array([ 0,  1,  3,  6,  7,  8,  9, 10, 11, 13]),)


* sorting

In [ ]:
arr = np.array([18,45,7,10,0,1,8,25,100,-9])
arr

array([ 18,  45,   7,  10,   0,   1,   8,  25, 100,  -9])

In [ ]:
np.sort(arr)   #asscending

array([ -9,   0,   1,   7,   8,  10,  18,  25,  45, 100])

In [ ]:
-np.sort(-arr)     #descending

array([100,  45,  25,  18,  10,   8,   7,   1,   0,  -9])


any() & all()

In [ ]:
newarr = np.array([2,4,6,8,10,18,45,10,7])
newarr

array([ 2,  4,  6,  8, 10, 18, 45, 10,  7])

In [ ]:
np.any(newarr % 2 == 0)         #returns true if atlest one element satisfy condition else false

True

In [ ]:
np.all(newarr % 2 == 0)          #returns true if all elements satisfy condition else false

False

resize()

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

delete(arr,obj,axis)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.delete(a,11)          #here; 11 is object/element for 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
delarr = np.array([[1,2,3],[4,3,5]])
delarr

array([[1, 2, 3],
       [4, 3, 5]])

In [ ]:
np.delete(delarr,3)      #here; 3 is index for 2D array

array([1, 2, 3, 3, 5])

In [ ]:
delarr

array([[1, 2, 3],
       [4, 3, 5]])

In [ ]:
np.delete(delarr,1, axis=0)

array([[1, 2, 3]])

* LCM

In [ ]:
arr = np.array([2,4,6,8,10])
arr

array([ 2,  4,  6,  8, 10])

In [ ]:
np.lcm.reduce(arr)

120

In [ ]:
num1=25
num2=625
num3=125
np.lcm.reduce((num1,num2,num3))

625

* GCD

In [ ]:
a=18
b=9

np.gcd(a,b)

9

In [ ]:
arr

array([ 2,  4,  6,  8, 10])

In [ ]:
np.gcd.reduce(arr)

2


* Linear Equation

In [ ]:
3x + y = 9
x + 2y = 8

In [ ]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])

In [ ]:
a

array([[3, 1],
       [1, 2]])

In [ ]:
b

array([9, 8])

In [ ]:
np.linalg.solve(a,b)

array([2., 3.])

* Quadractic Equation

In [ ]:
x^2 + 4x + 4 = 0

In [ ]:
coeff = np.array([1,4,4])

In [ ]:
np.roots(coeff)      #To find roots of quadratic equation

array([-2., -2.])

vdot()


In [ ]:
#v--->vector

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])


#logic
# 1*10 + 2*20 + .......... + 6*60

In [ ]:
np.vdot(a,b)

910

* mean()

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(a)

3.5

* weighted mean

In [ ]:
array = np.array([1,2,3,4])
weight = np.array([4,3,2,1])

#(1*4 + 2*3 + 3*2 + 4*1)/(4+3+2+1)

In [ ]:
np.average(array,weights=weight)

2.0

argsort()

In [ ]:
array = np.array([-10,0.3,1.5,19,-50, -3.5, 11.5, 9])
array

array([-10. ,   0.3,   1.5,  19. , -50. ,  -3.5,  11.5,   9. ])

In [ ]:
np.sort(array)

array([-50. , -10. ,  -3.5,   0.3,   1.5,   9. ,  11.5,  19. ])

In [ ]:
np.argsort(array)      #gives indices

array([4, 0, 5, 1, 2, 7, 6, 3])

square()  &  sqrt()

In [ ]:
arr =np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

In [ ]:
np.square(arr)

array([ 4, 16, 36, 64])

In [ ]:
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.82842712])